### ISSUE TITLE
[Editor|Debug] Keybinding gets stuck

### ISSUE THREAD

**Issue by MartijnKTue** [eclipse/poosl#35]
# Description

In normal "Poosl Edit" mode the F5 keybinding is bound to "Refresh". When you debug a model, you switch to the "Poosl debug" view the key is bound to "Step". However if you switch back the "Poosl Edit" key, it still is bound to "Step".

# What do I see

When trying to refresh (f.e. in the project explorer) after a debug session, the simulator will (try to) take a step and not refresh the view.

# What do I expect to see

The file Explorer to refresh.

# Version

Tested this on both linux and window with the latest version ( 1.0.2.v20220613).

**Comment by wpiers** [comment]
I reproduce this issue even with Eclipse Java debugger. F5 keeps on stepping into Java files whatever the current perspective is. As long as the POOSL debug session is running, the context is org.eclipse.poosl.rotalumisclient.debugcontext. We cannot deactivate this context when outside of the POOSL debug perspective, otherwise the "Resume/Stop" bindings won't work, and probably other things.

Unfortunately we won't be able to fix this issue. The workaround is to use the right-click > Refresh action.
