### ISSUE TITLE
poosl installation issue

### ISSUE THREAD

**Issue by yonghui-git** [eclipse/poosl#36]
When I try to install POOSL via eclipse, I get the following error info. Is it a problem with the firewall? If yes, could you tell me how to configure the proxy with Eclipse? Thanks.

Unable to read repository at https://eclipse.github.io/poosl/release/1.0.2/content.xml.
Unable to read repository at https://eclipse.github.io/poosl/release/1.0.2/content.xml.
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested targe
![poosl_error](https://user-images.githubusercontent.com/19535336/178953412-a9f1c576-6221-43e6-b365-3c9a299c0282.PNG)
t

**Comment by wpiers** [comment]
This error is due to your JVM missing a (or maybe several) certificate, it is most likely unrelated to POOSL and will happen with other updates sites. 

In short, when eclipse installs softwares it establishes a connection with updates sites. To do so it uses Java, thus the JVM eclipse is launched on must be properly parametrized to be able to access external URLs in a safe way. In your case, its certificates registry is missing the ones required to access our update site URL.

You can find plenty of resources online for "PKIX Path" issues. A shortcut could be simply to update your JVM to an earlier version. Otherwise you'll probably have to install the missing certificates like described here: https://magicmonster.com/kb/prg/java/ssl/pkix_path_building_failed/ . I didn't try it but it looks like a good solution candidate to solve your issue.

**Comment by wpiers** [comment]
I cannot reproduce this issue, please reopen if needed.
